### ISSUE TITLE
running getClusterSpecificPvalue on binary matrix

### ISSUE THREAD

**Issue by aditiq** [timydaley/scABC#3]
Hi,

I came across your package through your biorxiv paper.

Can the function getClusterSpecificPvalue be used on binary matrices? 
I am working with bulk atac seq data and generating a binary matrix (n*p) with each cell = 1 a peak n exists for sample p else 0. I can't use counts because of other issues. I am trying to use the function getClusterSpecificPvalue on this matrix to identify peaks specific to my pre-defined clusters of samples. 

1. Are any distribution assumptions being violated if I use a binary matrix with this function ?
2. I also assigned the background medians to be all 1 so that none of the sample get removed as well all of them get equal weightage. Do you see any issues with that ? 

Thanks for your help !

**Comment by linzx06** [comment]
Thank you for the interest in our package.

1. We assume a poisson assumption. You can implement the function using the
binary matrix, but there may be loss of power in identifying
cluster-specific peaks.
2. Yes, that is OK.

**Comment by aditiq** [comment]
Excellent - Thanks !

**Comment by timydaley** [comment]
To follow up, the Poisson assumption will give higher power for binary entries than a method such as DESeq2 or other methods for RNA-seq or scRNA-seq differential expression that use a Negative Binomial model.  
The question of how to determine cluster specific peaks using a binary matrix is interesting and is likely something that should be explored in more depth.
